- id: ppyupgrade
  name: PyUpgrade
  description: Automatically upgrade syntax for newer versions.
  entry: ppyupgrade
  language: python
  types: ["python"]
  files: ""
  minimum_pre_commit_version: 0.15.0
